id: P002940
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W23671
  title: བོད་ལྗོངས་ནགས་ཤོད་འབྲི་རུའི་ལོ་རྒྱུས་རབ་རིམ་སཱ་ལའི་ལྗོན་ཤིང
  author: ''
  volumes:
    4cad499117d0420b8a3b362d597e3610:
      image_group_id: I4265
      title: ''
      volume_number: 1
      total_pages: 510
      base_file: v001.txt
