id: I1EDBD7B7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T01:43:07+00:00'
last_modified: '2022-06-07T16:21:46.658131+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23671
  title: བོད་ལྗོངས་ནགས་ཤོད་འབྲི་རུའི་ལོ་རྒྱུས་རབ་རིམ་སཱ་ལའི་ལྗོན་ཤིང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    3E56:
      image_group_id: I4265
      title: ''
      total_pages: 510
      order: 1
      base_file: 3E56.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
